import type { ProcessContent } from "../types";

export const ofertowanie: ProcessContent = {
  slug: "ofertowanie",
  metaTitle: "Automatyzacja ofertowania: oferta z CRM, cennika i szablonu",
  metaDescription:
    "Jak działa zautomatyzowane przygotowanie ofert: dane z zapytania, kalkulacja z cennika, oferta z szablonu, akceptacja rabatów i follow-up. Etapy, warianty, koszty.",
  primaryKeyword: "automatyzacja ofertowania",
  updatedAt: "2026-10-04",
  hero: {
    eyebrow: "Proces: sprzedaż",
    title: "Automatyzacja ofertowania: od zapytania do wysłanej oferty",
    lead: "Handlowiec nie składa oferty od zera w Wordzie. Dane z zapytania trafiają do CRM, kalkulacja liczy się z aktualnego cennika, oferta powstaje z szablonu, a system pilnuje rabatów i przypomina o kontakcie. Pokazujemy krok po kroku, jak taki proces wygląda i co jest potrzebne, żeby go wdrożyć.",
    bullets: [
      "Oferta z szablonu i aktualnego cennika",
      "Akceptacja rabatów powyżej progu",
      "Przypomnienia o follow-upie i status w CRM",
    ],
  },
  summary: [
    { label: "Dla kogo", value: "Firmy B2B, które przygotowują oferty dopasowane do klienta" },
    { label: "Czas wdrożenia", value: "Zwykle kilka tygodni, zależnie od wariantu" },
    { label: "Narzędzia", value: "CRM, cennik, generator dokumentów, poczta" },
    { label: "Po waszej stronie", value: "Szef sprzedaży i osoba odpowiedzialna za cennik" },
  ],
  symptoms: {
    title: "Po czym poznać, że ofertowanie warto zautomatyzować",
    lead: "Jeśli rozpoznajecie u siebie dwa lub trzy z tych sygnałów, automatyzacja zwykle szybko się zwraca.",
    items: [
      "Handlowcy kopiują starą ofertę i ręcznie zmieniają nazwę klienta, pozycje i ceny.",
      "W ofertach zdarzają się nieaktualne ceny albo błędy w sumach.",
      "Każdy handlowiec ma własną wersję szablonu i oferty wyglądają różnie.",
      "Rabaty są udzielane bez wiedzy szefa sprzedaży albo czekają na jego zgodę mailem.",
      "Przygotowanie oferty zajmuje kilka dni, a klient w tym czasie dostaje ofertę od konkurencji.",
      "Nikt nie wie, ile ofert czeka na odpowiedź klienta i kiedy do nich wrócić.",
    ],
  },
  flow: {
    title: "Jak wygląda przygotowanie oferty po automatyzacji",
    lead: "Tak przechodzi oferta od zapytania klienta do decyzji. Kroki oznaczone jako automatyczne dzieją się bez udziału zespołu.",
    steps: [
      {
        title: "Zapytanie w CRM",
        body: "Zapytanie z formularza, maila lub telefonu trafia do CRM jako szansa sprzedaży, z przypisanym handlowcem. Dane klienta uzupełniają się z rejestrów po NIP.",
        actor: "System",
        automated: true,
        tool: "CRM, formularz, poczta",
      },
      {
        title: "Zebranie potrzeb",
        body: "AI wyciąga z treści zapytania i załączników produkty, ilości, terminy i wymagania. Handlowiec uzupełnia to, czego brakuje, w jednym formularzu.",
        actor: "Handlowiec",
        automated: false,
        tool: "CRM, AI do dokumentów",
      },
      {
        title: "Kalkulacja",
        body: "System liczy cenę z aktualnego cennika, uwzględnia warunki klienta, koszty dostawy i marżę. Handlowiec widzi wynik i może dodać pozycje lub rabat.",
        actor: "System",
        automated: true,
        tool: "Cennik, arkusz lub ERP",
      },
      {
        title: "Akceptacja rabatu",
        body: "Gdy rabat lub marża przekracza ustalony próg, szef sprzedaży dostaje prośbę o akceptację w Teams, mailu lub CRM, z podsumowaniem oferty.",
        actor: "Szef sprzedaży",
        automated: false,
        tool: "Teams, CRM",
      },
      {
        title: "Dokument oferty",
        body: "Oferta powstaje z firmowego szablonu: dane klienta, pozycje, ceny, warunki i termin ważności. AI może przygotować krótki opis dopasowany do potrzeb klienta, który handlowiec sprawdza.",
        actor: "System",
        automated: true,
        tool: "Generator dokumentów",
      },
      {
        title: "Wysyłka i zapis",
        body: "Handlowiec wysyła ofertę jednym kliknięciem. Dokument zapisuje się przy szansie w CRM, a etap zmienia się na „oferta wysłana”.",
        actor: "Handlowiec",
        automated: false,
        tool: "Poczta, CRM",
      },
      {
        title: "Follow-up",
        body: "Po ustalonej liczbie dni handlowiec dostaje zadanie kontaktu z klientem. Przed końcem ważności oferty system przypomina o niej jeszcze raz.",
        actor: "System",
        automated: true,
        tool: "CRM",
      },
      {
        title: "Decyzja klienta",
        body: "Przyjęta oferta uruchamia kolejny proces: zamówienie, umowę lub fakturę zaliczkową. Odrzucona trafia do raportu z powodem odrzucenia.",
        actor: "Handlowiec",
        automated: false,
        tool: "CRM, program do faktur",
      },
    ],
  },
  example: {
    title: "Ofertowanie przed i po automatyzacji",
    lead: "Przykład firmy usługowo-produkcyjnej, w której kilku handlowców przygotowuje oferty dopasowane do zapytań klientów.",
    rows: [
      { label: "Start oferty", before: "Kopia starej oferty w Wordzie.", after: "Szansa w CRM z danymi klienta i potrzebami z zapytania." },
      { label: "Ceny", before: "Szukanie aktualnego cennika w mailach.", after: "Kalkulacja z jednego, aktualnego cennika." },
      { label: "Rabaty", before: "Pytanie szefa mailem albo decyzja handlowca bez kontroli.", after: "Akceptacja powyżej progu z historią decyzji." },
      { label: "Dokument", before: "Różne wersje szablonu, ręczne sumy.", after: "Jeden szablon, sumy liczone automatycznie." },
      { label: "Follow-up", before: "Zależny od pamięci handlowca.", after: "Zadanie i przypomnienie przed końcem ważności oferty." },
    ],
    note: "To przykład ilustracyjny. Zakres zawsze ustalamy po rozmowie o waszym procesie.",
  },
  outcomes: {
    title: "Co się zmienia po wdrożeniu",
    items: [
      { title: "Szybsza odpowiedź", body: "Oferta powstaje w czasie potrzebnym na sprawdzenie kalkulacji, a nie na składanie dokumentu." },
      { title: "Mniej błędów", body: "Ceny pochodzą z jednego cennika, a sumy i warunki liczą się same." },
      { title: "Kontrola marży", body: "Rabaty powyżej progu wymagają akceptacji, a każda decyzja jest zapisana przy ofercie." },
      { title: "Żadna oferta nie ginie", body: "Każda wysłana oferta ma termin kolejnego kontaktu, a szef sprzedaży widzi, co czeka na decyzję klienta." },
    ],
  },
  implementation: {
    title: "Jak przebiega wdrożenie",
    lead: "Cztery etapy, po każdym wiecie, co zostało zrobione i co dalej. Przy każdym etapie piszemy, czego potrzebujemy od was.",
    phases: [
      {
        title: "Przegląd procesu",
        duration: "kilka dni",
        body: "Rozmawiamy z szefem sprzedaży i jednym lub dwoma handlowcami, przeglądamy przykładowe oferty i sprawdzamy, gdzie jest cennik i jak powstaje kalkulacja.",
        fromYou: "Godzina rozmowy, kilka przykładowych ofert różnego typu i aktualny cennik.",
      },
      {
        title: "Projekt oferty i zasad",
        duration: "około tygodnia",
        body: "Projektujemy szablon oferty, zasady kalkulacji, progi akceptacji rabatów i harmonogram follow-upów. Porządkujemy cennik, jeśli jest w kilku wersjach.",
        fromYou: "Decyzje o progach rabatowych, warunkach handlowych i wyglądzie oferty.",
      },
      {
        title: "Budowa i testy",
        duration: "zwykle 2–4 tygodnie",
        body: "Budujemy proces w waszym CRM i testujemy go na prawdziwych zapytaniach. Handlowcy przygotowują oferty równolegle starym i nowym sposobem.",
        fromYou: "Dostęp do CRM i jeden lub dwóch handlowców do testów.",
      },
      {
        title: "Start i opieka",
        duration: "stale",
        body: "Przełączamy cały zespół sprzedaży na nowy proces, prowadzimy krótkie szkolenie i dopracowujemy szablon na podstawie pierwszych tygodni.",
        fromYou: "Zgłaszanie uwag i informacja o zmianach w cenniku.",
      },
    ],
  },
  prerequisites: {
    title: "Co warto przygotować przed startem",
    lead: "Lista do przejścia po pierwszej rozmowie. Nie wszystko musi być gotowe od razu, część ustalamy razem.",
    items: [
      "Aktualny cennik w jednym miejscu, nawet jeśli dziś jest to arkusz.",
      "Zasady kalkulacji: marże, koszty dostawy, warunki dla stałych klientów.",
      "Obecny szablon oferty albo kilka ofert, które uważacie za wzorcowe.",
      "Progi rabatowe i informacja, kto akceptuje rabaty powyżej nich.",
      "Informacja, jakiego CRM używacie, albo decyzja o jego wyborze.",
      "Typowy czas, po którym warto wrócić do klienta z pytaniem o decyzję.",
      "Osoba po waszej stronie, która będzie właścicielem procesu.",
    ],
  },
  variants: {
    title: "Warianty rozwiązania",
    lead: "Zakres dobieramy do skali firmy. Można zacząć od podstawowego wariantu i rozbudowywać go później.",
    items: [
      {
        name: "Podstawowy",
        description: "Dla firm, które chcą przede wszystkim skończyć ze składaniem ofert w Wordzie.",
        includes: [
          "Szablon oferty generowany z danych w CRM",
          "Pozycje i ceny z jednego cennika",
          "Zapis oferty przy szansie sprzedaży",
          "Przypomnienie o follow-upie",
        ],
      },
      {
        name: "Rozszerzony",
        description: "Dla zespołów sprzedaży, w których ważna jest kontrola rabatów.",
        includes: [
          "Wszystko z wariantu podstawowego",
          "Kalkulacja z marżą, kosztami dostawy i warunkami klienta",
          "Akceptacja rabatów powyżej progu",
          "Odczyt zapytań i załączników przez AI",
          "Raport ofert: wysłane, przyjęte, odrzucone i powody",
        ],
      },
      {
        name: "Pełny",
        description: "Dla firm z rozbudowaną kalkulacją lub produktami konfigurowanymi.",
        includes: [
          "Wszystko z wariantu rozszerzonego",
          "Konfigurator produktów i wariantów",
          "Ceny i stany pobierane z ERP",
          "Akceptacja oferty przez klienta online",
          "Automatyczne zamówienie lub faktura zaliczkowa po przyjęciu",
        ],
      },
    ],
  },
  costFactors: {
    title: "Od czego zależy koszt",
    lead: "Każde wdrożenie wyceniamy osobno, przed startem. Na cenę wpływa przede wszystkim:",
    items: [
      "złożoność kalkulacji: prosty cennik czy konfiguracja z wieloma wariantami,",
      "stan cennika i to, ile pracy wymaga jego uporządkowanie,",
      "liczba szablonów ofert, np. dla różnych linii produktów lub języków,",
      "integracja z ERP i programem do faktur,",
      "koszty narzędzi, np. licencji CRM, generatora dokumentów i modeli AI.",
    ],
  },
  risks: {
    title: "Na co uważamy przy wdrożeniu",
    items: [
      { risk: "Cennik w systemie przestanie być aktualny.", mitigation: "Jedna osoba odpowiada za cennik, a zmiany wprowadza w jednym miejscu, z którego korzystają wszystkie oferty." },
      { risk: "Handlowcy wrócą do własnych szablonów.", mitigation: "Szablon projektujemy razem z nimi, a oferta spoza procesu nie trafia do raportu sprzedaży ani do akceptacji rabatu." },
      { risk: "AI źle zrozumie zapytanie klienta.", mitigation: "AI tylko podpowiada dane, a handlowiec zawsze sprawdza pozycje przed kalkulacją." },
      { risk: "Akceptacja rabatu spowolni ofertę.", mitigation: "Próg ustawiamy tak, żeby akceptacji wymagały tylko nietypowe przypadki, a prośba trafia tam, gdzie szef sprzedaży i tak pracuje." },
    ],
  },
  faq: [
    { question: "Czy potrzebujemy CRM, żeby zautomatyzować ofertowanie?", answer: "Najlepiej tak, bo oferta powinna być zapisana przy kliencie i szansie sprzedaży. Jeśli nie macie CRM, pomagamy go wybrać i wdrożyć, np. Pipedrive lub HubSpot, albo budujemy prostszą bazę ofert w Airtable." },
    { question: "Czy oferta może zachować nasz wygląd?", answer: "Tak. Szablon odtwarzamy na podstawie waszej obecnej oferty albo projektujemy nowy, w formacie PDF lub Word." },
    { question: "Czy AI napisze ofertę za handlowca?", answer: "AI pomaga odczytać zapytanie i przygotować opis dopasowany do klienta. Ceny, pozycje i warunki pochodzą z cennika i kalkulacji, a handlowiec sprawdza ofertę przed wysyłką." },
    { question: "Co, jeśli kalkulacja jest skomplikowana?", answer: "Odtwarzamy wasze zasady kalkulacji w systemie, a przy wielu wariantach budujemy konfigurator. Najpierw opisujemy reguły razem z osobą, która dziś liczy oferty." },
    { question: "Czy klient może zaakceptować ofertę online?", answer: "Tak, w wariancie pełnym. Akceptacja przez link uruchamia od razu zamówienie, umowę lub fakturę zaliczkową." },
    { question: "Na czym to działa technicznie?", answer: "Zwykle na CRM, takim jak Pipedrive lub HubSpot, połączonym z generatorem dokumentów i platformą automatyzacji, np. Make lub n8n. Narzędzia dobieramy do tego, czego już używacie." },
    { question: "Ile trwa wdrożenie?", answer: "Wariant podstawowy zwykle kilka tygodni. Konfigurator produktów i integracja z ERP wydłużają projekt. Dokładny plan podajemy po przeglądzie procesu." },
  ],
  relatedServiceSlugs: ["automatyzacja-sprzedazy", "automatyzacja-dla-firm-uslugowych", "integracje-systemow"],
  relatedToolSlugs: ["pipedrive", "hubspot", "make", "chatgpt"],
  relatedArticleSlugs: ["automatyzacja-obslugi-leadow-sprzedazowych", "integracja-crm-z-fakturowaniem", "jak-mierzyc-roi-automatyzacji"],
};
